"use strict";
jQuery(function ($) {
    $('#woocs_auto_switcher_skin').on("change",function () {
        var woocs_side_switcher_skin = $(this).val();
        if (woocs_side_switcher_skin == 'roll_blocks') {
            $('.woocs_roll_blocks_width').show(200);
        } else {
            $('.woocs_roll_blocks_width').hide(200);
        }
    });
    $('#woocs_is_multiple_allowed').on("change",function () {
        var woocs_is_multiple_allowed = parseInt($(this).val(), 10);
        var woocs_is_fixed_enabled = parseInt($('#woocs_is_fixed_enabled').val(), 10);
        //***
        if (woocs_is_multiple_allowed) {
            $('#woocs_is_fixed_enabled').parents('tr').show(200);
            $('#woocs_is_fixed_coupon').parents('tr').show(200);
            $('#woocs_is_fixed_shipping').parents('tr').show(200);
            if (woocs_is_fixed_enabled) {
                $('#woocs_force_pay_bygeoip_rules').parents('tr').show(200);
            }
        } else {
            $('#woocs_is_fixed_enabled').parents('tr').hide(200);
            $('#woocs_is_fixed_coupon').parents('tr').hide(200);
            $('#woocs_is_fixed_shipping').parents('tr').hide(200);
            $('#woocs_force_pay_bygeoip_rules').parents('tr').hide(200);
        }
    });
    $('#woocs_is_auto_switcher').on("change",function () {
        var woocs_is_auto_switcher = parseInt($(this).val(), 10);
        //***
        if (woocs_is_auto_switcher) {
            $('#woocs_auto_switcher_skin').parents('tr').show(200);
            $('#woocs_auto_switcher_side').parents('tr').show(200);
            $('#woocs_auto_switcher_top_margin').parents('tr').show(200);
            $('#woocs_auto_switcher_color').parents('tr').show(200);
            $('#woocs_auto_switcher_hover_color').parents('tr').show(200);
            $('#woocs_auto_switcher_basic_field').parents('tr').show(200);
            $('#woocs_auto_switcher_additional_field').parents('tr').show(200);
            $('#woocs_auto_switcher_show_page').parents('tr').show(200);
            $('#woocs_auto_switcher_hide_page').parents('tr').show(200);
            $('#woocs_auto_switcher_mobile_show').parents('tr').show(200);
        } else {
            $('#woocs_auto_switcher_skin').parents('tr').hide(200);
            $('#woocs_auto_switcher_side').parents('tr').hide(200);
            $('#woocs_auto_switcher_top_margin').parents('tr').hide(200);
            $('#woocs_auto_switcher_color').parents('tr').hide(200);
            $('#woocs_auto_switcher_hover_color').parents('tr').hide(200);
            $('#woocs_auto_switcher_basic_field').parents('tr').hide(200);
            $('#woocs_auto_switcher_additional_field').parents('tr').hide(200);
            $('#woocs_auto_switcher_show_page').parents('tr').hide(200);
            $('#woocs_auto_switcher_hide_page').parents('tr').hide(200);
            $('#woocs_auto_switcher_mobile_show').parents('tr').hide(200);

        }
    });

    $('#woocs_is_fixed_enabled').on("change",function () {
        var val = parseInt($(this).val(), 10);

        if (val) {
            if (!confirm("Native woocommerce price filter doesn't see data generated by this feature (for the time being) - its does not see fixed prices. Do you agree use this feature anyway?")) {
                val = 0;
                $(this).val(val);
            }
        }

        if (val) {
            $('#woocs_force_pay_bygeoip_rules').parents('tr').show(200);
        } else {
            $('#woocs_force_pay_bygeoip_rules').parents('tr').hide(200);
        }
    });


    $('#woocs_is_geoip_manipulation').on("change",function () {
        var val = parseInt($(this).val(), 10);

        if (val) {
            if (!confirm("Native woocommerce price filter doesn't see data generated by this feature (for the time being) - its does not see prices defined by individual geo ip rules. Do you agree use this feature anyway?")) {
                val = 0;
                $(this).val(val);
            }
        }

    });


});

