<?php

/**
 * An array of flat rate boxes sizes for USPS
 */
return array(
	"USPS"	=>	array(
		"FlatRateEnvelope"     => array(
			"name"     => "Letter Envelope",
			"length"   => "12.5",
			"width"    => "9.5",
			"height"   => "1",
			"weight"   => "70",
			"type"     => "envelope",
		),
		"FlatRateGiftCardEnvelope"     => array(
			"name"     => "Gift Card Envelopes",
			"length"   => "10",
			"width"    => "7",
			"height"   => "0.25",
			"weight"   => "70",
			"type"     => "envelope",
		),
		"FlatRateWindowEnvelope"     => array(
			"name"     => "Window Envelopes",
			"length"   => "10",
			"width"    => "5",
			"height"   => "0.25",
			"weight"   => "70",
			"type"     => "envelope",
		),
		"SmallFlatRateEnvelope"     => array(
			"name"     => "Small Envelopes",
			"length"   => "10",
			"width"    => "6",
			"height"   => "0.25",
			"weight"   => "70",
			"type"     => "envelope",
		),
		"FlatRatePaddedEnvelope"     => array(
			"name"     => "Padded Envelopes",
			"length"   => "12.5",
			"width"    => "9.5",
			"height"   => "1",
			"weight"   => "70",
			"type"     => "envelope",
		),
		"FlatRateLegalEnvelope"     => array(
			"name"     => "Legal Envelopes",
			"length"   => "15",
			"width"    => "9.5",
			"height"   => "0.25",
			"weight"   => "70",
			"type"     => "envelope",
		),
		"SmallFlatRateBox"     => array(
			"name"     => "Small Box",
			"length"   => "8.6875",
			"width"    => "5.4375",
			"height"   => "1.75",
			"weight"   => "70",
		),
		"MediumFlatRateBox"     => array(
			"name"     => "Medium Box - 1",
			"length"   => "11.25",
			"width"    => "8.75",
			"height"   => "6",
			"weight"   => "70",
		),
		"MediumFlatRateBox_b"     => array(
			"name"     => "Medium Box - 2",
			"length"   => "14",
			"width"    => "12",
			"height"   => "3.5",
			"weight"   => "70",
		),
		"LargeFlatRateBox"     => array(
			"name"     => "Large Box",
			"length"   => "12.25",
			"width"    => "12.25",
			"height"   => "6",
			"weight"   => "70",
		),
		"LargeFlatRateBoardGameBox"     => array(
			"name"     => "Large Board Game Box",
			"length"   => "23.6875",
			"width"    => "11.75",
			"height"   => "3",
			"weight"   => "70",
		),
		"Card-1"     => array(
			"name"     => "Card - 1",
			"length"   => "3.5",
			"width"    => "5.5",
			"height"   => "1",
			"weight"   => "15",
		),
		"Card-2"     => array(
			"name"     => "Card - 2",
			"length"   => "4.25",
			"width"    => "6",
			"height"   => "1",
			"weight"   => "15",
		),
		"Letter-1"     => array(
			"name"     => "Letter - 1",
			"length"   => "3.5",
			"width"    => "5.5",
			"height"   => "1",
			"weight"   => "3.5",
		),
		"Letter-2"     => array(
			"name"     => "Letter - 2",
			"length"   => "6.125",
			"width"    => "11.5",
			"height"   => "1",
			"weight"   => "3.5",
		),
		"Flat-1"     => array(
			"name"     => "Flat - 1",
			"length"   => "6.125",
			"width"    => "11.5",
			"height"   => "1",
			"weight"   => "13",
		),
		"Flat-2"     => array(
			"name"     => "Flat - 2",
			"length"   => "12",
			"width"    => "15",
			"height"   => "1",
			"weight"   => "13",
		),
		"FlatRateCardboardEnvelope"     => array(
			"name"     => "Cardboard Envelope",
			"length"   => "12.5",
			"width"    => "9.5",
			"height"   => "1",
			"weight"   => "70",
		),
		"RegionalRateBoxA-1"     => array(
			"name"     => "Regional Rate Box A - 1",
			"length"   => "10.125",
			"width"    => "7.125",
			"height"   => "5",
			"weight"   => "15",
		),
		"RegionalRateBoxA-2"     => array(
			"name"     => "Regional Rate Box A - 2",
			"length"   => "16.166",
			"width"    => "11.166",
			"height"   => "2.5",
			"weight"   => "15",
		),
		"RegionalRateBoxB-1"     => array(
			"name"     => "Regional Rate Box B - 1",
			"length"   => "12.25",
			"width"    => "10.5",
			"height"   => "5.5",
			"weight"   => "20",
		),
		"RegionalRateBoxB-2"     => array(
			"name"     => "Regional Rate Box B - 2",
			"length"   => "16.25",
			"width"    => "14.5",
			"height"   => "3",
			"weight"   => "15",
		),
		"LargeFlatRateBoardGameBox-1"     => array(
			"name"     => "Large Flat Rate Board Game Box - 1",
			"length"   => "23.687",
			"width"    => "11.75",
			"height"   => "3",
			"weight"   => "70",
		),
		"LargeFlatRateBoardGameBox-2"     => array(
			"name"     => "Large Flat Rate Board Game Box - 2",
			"length"   => "24.062",
			"width"    => "11.875",
			"height"   => "3.125",
			"weight"   => "70",
		),
	),
);
